---
# handlers file for ansible-role-elk

- name: Reload Daemon
  systemd: daemon_reload=yes

- name: Enable Elasticsearch
  service:
    name: elasticsearch
    enabled: yes

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started

